### ISSUE TITLE
zippyshare links are not absolute and show a 404 page

### ISSUE THREAD

**Issue by goggamesissue** [MachineGunnur/GOG-Games#92] opened 2019-10-11 13:00 UTC
`https://goggamespc7v6z5e.onion.ws/https://www96.zippyshare.com/v/qHvpq7vs/file.html`

That is the URL that opens in a new tab if you click on a zippyshare link. You have to manually remove the `https://goggamespc7v6z5e.onion.ws/` part for the zippyshare page to load properly.

I'm guessing that the HREF for the <a> tag includes a leading `/` which is making it a relative path?

**Comment by guedela** [comment] 2019-10-11 15:15
Excuse me if I am wrong but cannot reproduce by the above.

How is it Possible? I opened up both the mirror and Onion in the latest version of Firefox with enabled JavaScript, clicked a link, works, the copy button works. What the browser doesn't, exactly?

I even disabled JS, works. Please try Tor Browser, might help.

**Comment by MachineGunnur** [comment] 2019-10-11 16:59
same issue as: https://github.com/MachineGunnur/GOG-Games/issues/13 
closing.

use tor browser or use jdownloader 2 + clip board icon on .ws site. it will parse links and grab the real ones.

**Closed by MachineGunnur** 2019-10-11 16:59 UTC
